name = "Republic"
uuid = "27243419-9dde-4721-b67c-fd63626fea7f"
authors = ["AntonOresten <antonoresten@proton.me> and contributors"]
version = "0.0.4"

[workspace]
projects = ["test"]

[compat]
julia = "1.11"
